### PR TITLE
Teach build.sh to support building on MacOS.

### PR DESCRIPTION
**Pull request by Arnaud-de-Grandmaison-ARM**

### CODE REVIEW

**Comment by james-whitaker-arm** [comment]
Thanks for the contribution @Arnaud-de-Grandmaison-ARM. The intention was to only support Linux, but I don't see a reason not to get this building on MacOS.

Might sound obvious, but can I confirm you've tested the build on a MacOS device? I haven't tried myself yet but will give it a go later this week.

**Comment by Arnaud-de-Grandmaison-ARM** [comment]
My development machine is actually a MacOS device, which is why I bumped on the issue and suggested this fix --- and I can confirm it works on MacOS --- and linux, as I'm running the tests on both.

FWIW, I have a couple more patches to significantly reduce build time & library size as well as to add Linux / MacOS CI (with github workflows) for disassembly-library.

**Review by james-whitaker-arm — APPROVED** [review]

**Review by james-whitaker-arm — CHANGES_REQUESTED** [review]
Thanks this looks good.

There are some other small changes required in order to support the Python bindings:

1.  In python/pyproject.toml, this needs to be changed to include the .dylib file:
```[tool.setuptools.package-data]
"armdisasm" = ["*.py", "libarmdisasm.so"]
```

2.  Line 33 of python/armdisasm/armdisasm.py needs to be changed to support both .so and .dylib:
```
LIBARMDISASM = "libarmdisasm.so"   # Name of the library's shared object file.
```

3.  The `.gitignore` file in the project root should probably include `*.dylib`

4.  Line 226 of build.sh should be changed to something like "# Copy the libarmdisasm library into the python package structure"

5.  The README.md file mentions ".so" in a few places, these should be changed to just "libarmdisasm"

**Comment by Arnaud-de-Grandmaison-ARM** [comment]
I've updated the patch with the changes you requested.
My testing went further than previously (which was solely relying on the testing done by `build.sh`), as I have been able to `pip install` the generated wheel file and use `examples/api_demo.py`

**Review by james-whitaker-arm — APPROVED** [review]
Thanks Arnaud, looks good to me. I'll make sure these changes get mirrored internally too.

**Pull request merged**
